### ISSUE TITLE
运行pre_process部分报错

### ISSUE THREAD

**Issue by jyx147** [LiUzHiAn/hf2vad#11]
您好，我安装reamme.md的内容，执行了data preprocessing部分，但是我在运行extract_bboxes.py的时候报错了。请问一下这个问题咋解决，或者您可以把pre_process执行完之后生成的文件打包给我吗？谢谢大佬！
C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\mmdet\models\builder.py:51: UserWarning: train_cfg and test_cfg is deprecated, please specify them in model
  warnings.warn(
load checkpoint from local path: assets/cascade_rcnn_r101_fpn_1x_coco_20200317-0b6a2fbf.pth
  0%|          | 0/2550 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "D:/workspace/hf2vad-master/hf2vad/pre_process/extract_bboxes.py", line 161, in <module>
    obj_bboxes_extraction(dataset_root=os.path.join(args.proj_root, "data"),
  File "D:/workspace/hf2vad-master/hf2vad/pre_process/extract_bboxes.py", line 138, in obj_bboxes_extraction
    obj_bboxes = getObjBboxes(cur_img, mm_det_model, dataset_name)
  File "D:/workspace/hf2vad-master/hf2vad/pre_process/extract_bboxes.py", line 21, in getObjBboxes
    result = inference_detector(model, img)
  File "D:\workspace\hf2vad-master\hf2vad\pre_process\mmdet_utils.py", line 91, in inference_detector
    result = model(return_loss=False, rescale=True, **data)[0]
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\mmcv\runner\fp16_utils.py", line 109, in new_func
    return old_func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\mmdet\models\detectors\base.py", line 174, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\mmdet\models\detectors\base.py", line 147, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\mmdet\models\detectors\two_stage.py", line 179, in simple_test
    proposal_list = self.rpn_head.simple_test_rpn(x, img_metas)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\mmdet\models\dense_heads\dense_test_mixins.py", line 130, in simple_test_rpn
    proposal_list = self.get_bboxes(*rpn_outs, img_metas=img_metas)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\mmcv\runner\fp16_utils.py", line 197, in new_func
    return old_func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\mmdet\models\dense_heads\base_dense_head.py", line 102, in get_bboxes
    results = self._get_bboxes_single(cls_score_list, bbox_pred_list,
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\mmdet\models\dense_heads\rpn_head.py", line 185, in _get_bboxes_single
    return self._bbox_post_process(mlvl_scores, mlvl_bbox_preds,
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\mmdet\models\dense_heads\rpn_head.py", line 231, in _bbox_post_process
    dets, _ = batched_nms(proposals, scores, ids, cfg.nms)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\mmcv\utils\config.py", line 48, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'nms'

Process finished with exit code 1

**Comment by jyx147** [comment]
这是我的邮箱，1476055806@qq.com，求大佬帮忙！

**Comment by LiUzHiAn** [comment]
看起来像是 mmdetection相关的问题，请问你装的mmcv和mmdet的版本是正确的吗？

由于预处理得到的文件比较大，抱歉我没办法直接分享，可能还需要你自己处理一下相关的环境问题。另外，我没有在windows上测试过。

**Comment by Smallwhite999** [comment]
> 看起来像是 mmdetection相关的问题，请问你装的mmcv和mmdet的版本是正确的吗？
> 
> 由于预处理得到的文件比较大，抱歉我没办法直接分享，可能还需要你自己处理一下相关的环境问题。另外，我没有在windows上测试过。

您好，能否将预处理得到的数据分享一下啊？如百度云链接之类的，十分感谢。

**Comment by jyx147** [comment]
数据集太大了，avenue处理完就60G，不好意思！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LiUzHiAn/hf2vad"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月14日(星期一) 晚上7:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LiUzHiAn/hf2vad] 运行pre_process部分报错 (Issue #11)





  
看起来像是 mmdetection相关的问题，请问你装的mmcv和mmdet的版本是正确的吗？
 
由于预处理得到的文件比较大，抱歉我没办法直接分享，可能还需要你自己处理一下相关的环境问题。另外，我没有在windows上测试过。
  
您好，能否将预处理得到的数据分享一下啊？如百度云链接之类的，十分感谢。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Smallwhite999** [comment]
> 数据集太大了，avenue处理完就60G，不好意思！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "LiUzHiAn/hf2vad" ***@***.***&gt;; 发送时间:&nbsp;2022年3月14日(星期一) 晚上7:53 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [LiUzHiAn/hf2vad] 运行pre_process部分报错 (Issue #11) 看起来像是 mmdetection相关的问题，请问你装的mmcv和mmdet的版本是正确的吗？ 由于预处理得到的文件比较大，抱歉我没办法直接分享，可能还需要你自己处理一下相关的环境问题。另外，我没有在windows上测试过。 您好，能否将预处理得到的数据分享一下啊？如百度云链接之类的，十分感谢。 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

您好，你是否在linux上复现成功了？我在数据预处理阶段遇到了很多麻烦，尝试了很多方法也没有解决，能否告知一下您的pytorch和cuda的相关配置，非常感谢。我按照上面配置说明进行配置的，卡是3090的cuda为11.1，但总是报一些cuda相关的系统错误

**Comment by nono-zz** [comment]
我也遇到了这样的错误，'ConfigDict' object has no attribute 'nms'，能告知mmcv和mmdet你安装的是什么版本吗？我的mmcv=1.4.7，mmdet=2.22.0， torch=1.7.0, cuda=10.1。

**Comment by zjd1836** [comment]
不好意思，请问您的问题解决了吗？

**Comment by yinyexingchen** [comment]
> 您好，我安装reamme.md的内容，执行了data preprocessing部分，但是我在运行extract_bboxes.py的时候报错了。请问一下这个问题咋解决，或者您可以把pre_process执行完之后生成的文件打包给我吗？谢谢大佬！ C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\mmdet\models\builder.py:51: UserWarning: train_cfg and test_cfg is deprecated, please specify them in model warnings.warn( load checkpoint from local path: assets/cascade_rcnn_r101_fpn_1x_coco_20200317-0b6a2fbf.pth 0%| | 0/2550 [00:04<?, ?it/s] Traceback (most recent call last): File "D:/workspace/hf2vad-master/hf2vad/pre_process/extract_bboxes.py", line 161, in obj_bboxes_extraction(dataset_root=os.path.join(args.proj_root, "data"), File "D:/workspace/hf2vad-master/hf2vad/pre_process/extract_bboxes.py", line 138, in obj_bboxes_extraction obj_bboxes = getObjBboxes(cur_img, mm_det_model, dataset_name) File "D:/workspace/hf2vad-master/hf2vad/pre_process/extract_bboxes.py", line 21, in getObjBboxes result = inference_detector(model, img) File "D:\workspace\hf2vad-master\hf2vad\pre_process\mmdet_utils.py", line 91, in inference_detector result = model(return_loss=False, rescale=True, **data)[0] File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\mmcv\runner\fp16_utils.py", line 109, in new_func return old_func(*args, **kwargs) File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\mmdet\models\detectors\base.py", line 174, in forward return self.forward_test(img, img_metas, **kwargs) File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\mmdet\models\detectors\base.py", line 147, in forward_test return self.simple_test(imgs[0], img_metas[0], **kwargs) File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\mmdet\models\detectors\two_stage.py", line 179, in simple_test proposal_list = self.rpn_head.simple_test_rpn(x, img_metas) File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\mmdet\models\dense_heads\dense_test_mixins.py", line 130, in simple_test_rpn proposal_list = self.get_bboxes(*rpn_outs, img_metas=img_metas) File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\mmcv\runner\fp16_utils.py", line 197, in new_func return old_func(*args, **kwargs) File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\mmdet\models\dense_heads\base_dense_head.py", line 102, in get_bboxes results = self._get_bboxes_single(cls_score_list, bbox_pred_list, File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\mmdet\models\dense_heads\rpn_head.py", line 185, in _get_bboxes_single return self._bbox_post_process(mlvl_scores, mlvl_bbox_preds, File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\mmdet\models\dense_heads\rpn_head.py", line 231, in _bbox_post_process dets, _ = batched_nms(proposals, scores, ids, cfg.nms) File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\mmcv\utils\config.py", line 48, in **getattr** raise ex AttributeError: 'ConfigDict' object has no attribute 'nms'
> 
> Process finished with exit code 1

大佬您好，我想请教一下，您在抽取光流的时候，这个指令在windows平台上是如何解决的呢build the customer layers via executing install_custome_layers.sh.
