### ISSUE TITLE
cascade RCNN pretrained weights download error

### ISSUE THREAD

**Issue by MAXxYe** [LiUzHiAn/hf2vad#2]
Hello, I got a problem of donwloading mmdetection pretrain model.

Downloading: "https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmdetection/v2.0/cascade_rcnn/cascade_rcnn_r101_fpn_1x_coco/cascade_rcnn_r101_fpn_1x_coco_20200317-0b6a2fbf.pth" to /home/tianye/.cache/torch/hub/checkpoints/cascade_rcnn_r101_fpn_1x_coco_20200317-0b6a2fbf.pth
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tianye/mmdetection/mmdet/apis/inference.py", line 43, in init_detector
    checkpoint = load_checkpoint(model, checkpoint, map_location=map_loc)
  File "/home/tianye/anaconda3/envs/hf2vad/lib/python3.6/site-packages/mmcv/runner/checkpoint.py", line 513, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/home/tianye/anaconda3/envs/hf2vad/lib/python3.6/site-packages/mmcv/runner/checkpoint.py", line 451, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/home/tianye/anaconda3/envs/hf2vad/lib/python3.6/site-packages/mmcv/runner/checkpoint.py", line 244, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/home/tianye/anaconda3/envs/hf2vad/lib/python3.6/site-packages/mmcv/runner/checkpoint.py", line 284, in load_from_http
    filename, model_dir=model_dir, map_location=map_location)
  File "/home/tianye/anaconda3/envs/hf2vad/lib/python3.6/site-packages/torch/hub.py", line 553, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/home/tianye/anaconda3/envs/hf2vad/lib/python3.6/site-packages/torch/hub.py", line 419, in download_url_to_file
    u = urlopen(req)
  File "/home/tianye/anaconda3/envs/hf2vad/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/home/tianye/anaconda3/envs/hf2vad/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/home/tianye/anaconda3/envs/hf2vad/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/tianye/anaconda3/envs/hf2vad/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/home/tianye/anaconda3/envs/hf2vad/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/tianye/anaconda3/envs/hf2vad/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

Would you like to upload the cascade RCNN pretrained weights which your paper used?  It could definetely  be useful to any other ones who want to train their own ML-MemAE-SC model. Thanks so much~

**Comment by MAXxYe** [comment]
Sry, It turns out  I can download model at https://github.com/open-mmlab/mmdetection/tree/master/configs/cascade_rcnn 
My fault
